// <auto-generated />
namespace freezerbot.Migrations

open System
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion
open Npgsql.EntityFrameworkCore.PostgreSQL.Metadata

[<DbContext(typeof<RepositoryModel.RepositoryContext>)>]
type RepositoryContextModelSnapshot() =
    inherit ModelSnapshot()

    override this.BuildModel(modelBuilder: ModelBuilder) =
        modelBuilder
            .HasAnnotation("ProductVersion", "6.0.16")
            .HasAnnotation("Relational:MaxIdentifierLength", 63) |> ignore

        modelBuilder.Entity("RepositoryModel+Approval", (fun b ->

            b.Property<int>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                |> ignore

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id")) |> ignore

            b.Property<Nullable<int>>("RequestId")
                .IsRequired(false)
                .HasColumnType("integer")
                |> ignore

            b.Property<string>("User")
                .IsRequired(true)
                .HasColumnType("text")
                |> ignore

            b.HasKey("Id")
                |> ignore


            b.HasIndex("RequestId")
                |> ignore

            b.ToTable("Approvals") |> ignore

        )) |> ignore

        modelBuilder.Entity("RepositoryModel+Repository", (fun b ->

            b.Property<string>("Name")
                .IsRequired(true)
                .HasColumnType("text")
                |> ignore

            b.Property<bool>("Frozen")
                .IsRequired(true)
                .HasColumnType("boolean")
                |> ignore

            b.HasKey("Name")
                |> ignore


            b.ToTable("Repositories") |> ignore

        )) |> ignore

        modelBuilder.Entity("RepositoryModel+UnfreezeRequest", (fun b ->

            b.Property<int>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("integer")
                |> ignore

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id")) |> ignore

            b.Property<string>("Branch")
                .IsRequired(true)
                .HasColumnType("text")
                |> ignore

            b.Property<string>("RepositoryName")
                .IsRequired(true)
                .HasColumnType("text")
                |> ignore

            b.HasKey("Id")
                |> ignore


            b.HasIndex("RepositoryName")
                |> ignore

            b.ToTable("UnfreezeRequests") |> ignore

        )) |> ignore
        modelBuilder.Entity("RepositoryModel+Approval", (fun b ->
            b.HasOne("RepositoryModel+UnfreezeRequest", "Request")
                .WithMany()
                .HasForeignKey("RequestId")
                |> ignore

        )) |> ignore
        modelBuilder.Entity("RepositoryModel+UnfreezeRequest", (fun b ->
            b.HasOne("RepositoryModel+Repository", "Repository")
                .WithMany()
                .HasForeignKey("RepositoryName")
                |> ignore

        )) |> ignore

